### ISSUE TITLE
Cannot issue chained credential

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/keria#135]
I encountered an issue when trying to issue a chained credential from a signify issuer to a signify holder. See reproduction script here: https://github.com/WebOfTrust/signify-ts/pull/144

Please also refer to discord discussion:

> Yeah, there appears to be a missing step in KERIA and I'm not sure where it should go.  When you grant a credential to another AID, you need to send over any supporting data like registry events, registry anchoring events and all chained credentials (and all their associated events).  We handle this in the grant kli command, but because in KERIA we issue the grant via the generic exchanges endpoint, there is no where to put this functionality.
> Probaby, like the admit endpoint that has to parse and save the credential, we need a grant endpoint that streams out the supporting data.

From @pfeairheller 

# Actual result

Script keeps printing "[]", which is the list of credentials received from the holders agent.

# Expected result 

Script should print the credential and exit.

**Comment by nkongsuwan** [comment]
I had a similar problem with kli as well. So it is good to know someone else had a similar problem.
