### ISSUE TITLE
Name parameter is not needed for GET credentials by SAID endpoint

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/keria#142]
Similarly what was changed here: https://github.com/WebOfTrust/keria/pull/128, the name parameter is not used for GET /identifiers/{name}/credentials/{said} endpoint. See here: https://github.com/WebOfTrust/keria/blob/9dda515a7a1979da9503a9bff375d7dc6ac07a1c/src/keria/app/credentialing.py#L520

We only check that the name is a valid hab for this agent, then we proceed without using the hab. I suggest to move the endpoint to be

```
GET /credentials/{said}
```

to avoid having to pass the redundant `name` parameter when you have the credential id.

**Comment by m00sey** [comment]
Suggestion to remove name `param`

**Comment by lenkan** [comment]
Fixed by #179
