### ISSUE TITLE
Provide a way to view long running operations for an agent

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/keria#156]
Do you think it is a good idea to expose an endpoint for listing the active long running operations for an agent? I guess mainly for debugging purposes.

One use case example would be to see if a delegate operation is waiting to be resolved. Currently, only `GET /operations/{operation name}` and `DELETE /operations/{operation.name}` are exposed.

At first glance it looks fairly straightforward to implement, so I can take a look at implementing it. But first wanted to make sure it makes sense.

**Comment by psteniusubi** [comment]
I have an implementation of this here https://github.com/psteniusubi/keria/tree/feat-get-operations-list

I've found it useful in integration testing to make sure all long running operations have been handled.

I can create a PR if it is useful.

**Comment by psteniusubi** [comment]
I remember now that creating unit tests for this was a challenge. That's why I didn't create a PR. I'll see if I can create a test for this.

**Comment by kentbull** [comment]
I like this idea. Being able to get all long running operations would be good for monitoring as well.

**Comment by lenkan** [comment]
Resolved with #158
