### ISSUE TITLE
Signify-TS's challenge-response is broken due to recent change 

### ISSUE THREAD

**Issue by nkongsuwan** [WebOfTrust/keria#186]
KERIA is currently out-of-sync with Signify-TS due to the update on [Feb 1](https://github.com/WebOfTrust/signify-ts/commit/1e258b8d40e7952a00e303fc7d569cb1529f3acb).

As a result, the [`challenge.test.ts` ](https://github.com/WebOfTrust/signify-ts/blob/development/examples/integration-scripts/challenge.test.ts) is now failing.

**Comment by pfeairheller** [comment]
The release candidate branch is in sync with the development branch of Signify-TS.   I've pushed a new container to match
