### ISSUE TITLE
Provide a way to re-submit AID KEL to witnesses

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/keria#235]
If a witness is missing data, for example as a result of the issue described in https://github.com/WebOfTrust/keripy/issues/762, we need a way to re-submit the KEL of an AID to its witnesses. Similar to the `kli witness submit` command.

Quote from issue:

> Can this be repaired? KERIA probably not. From command line witness submit could catch it up. Possibly 'witness submit' in KERIA could be a workaround.

**Comment by 2byrds** [comment]
fixed by https://github.com/WebOfTrust/keria/pull/271
