### ISSUE TITLE
Docker image uses wrong version of keri

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/keria#263]
The dockerfile uses 1.2.0-dev6 currently, but setup.py points to 1.2.0-dev8.

See: 

- https://github.com/WebOfTrust/keria/blob/6bdb6087d51786f4e15ed59b8c274873238438fb/images/keria.dockerfile#L1
- https://github.com/WebOfTrust/keria/blob/6bdb6087d51786f4e15ed59b8c274873238438fb/setup.py#L79

Imo, we should use a python base image and install the dependencies using pip instead. What do you think?

**Comment by m00sey** [comment]
I pushed an updated Keri image: https://hub.docker.com/repository/docker/weboftrust/keria/general

I have no opinion on the rest of this.

**Comment by 2byrds** [comment]
Thank you @m00sey ! @lenkan happy to discuss the image version. My intention for having it build from the keri image rather than a base image is that there is quite a bit of setup for the keripy related env for the image and i did a lot of testing with that version of the keripy image. Also we do pip install specific versions from requirements https://github.com/WebOfTrust/keria/blob/main/images/keria.dockerfile#L10

**Comment by iFergal** [comment]
@2byrds The change means we can't build KERIA images on arm64 now. Keripy is published as 2 separate docker tags for each architecture. But ideally, there would actually be one tag for that which would resolve it - not sure what's involved there yet.

On this issue in general, I feel like Daniel's approach is more correct but the image build times are a killer. Conflicted :P

**Comment by 2byrds** [comment]
> @2byrds The change means we can't build KERIA images on arm64 now. Keripy is published as 2 separate docker tags for each architecture. But ideally, there would actually be one tag for that which would resolve it - not sure what's involved there yet.
> 
> On this issue in general, I feel like Daniel's approach is more correct but the image build times are a killer. Conflicted :P 

Architecture support is a necessity imo, I'll revert it back to a base python image until we can find a better path

**Comment by 2byrds** [comment]
@lenkan @iFergal PR to revert image build logic has been submitted https://github.com/WebOfTrust/keria/pull/274. Thank you for the discussion/info!

**Comment by tibor19** [comment]
If build time is a problem, we can have a common base image with all the necessary packages, or we can try to adopt a multi-stage approach.
