### ISSUE TITLE
Provide a way to protect the boot endpoint

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/keria#327]
### Feature request description/rationale

I suggest there should be a way to protect the boot endpoint with some simple authentication. In my opinion, this is convenient even if the boot port is not exposed publicly on the internet. It would also make it easier for people to spin up a KERIA instance publicly without having to worry about unauthorized people booting agents.

# Suggestion

Implement a [Basic authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication) check by configuring the keria boot endpoint with a `username` and a `password`. Like this:

```
keria start --boot-username username --boot-password password --boot 3903
```

Or, using environment variables

```
export KERIA_BOOT_USERNAME=username
export KERIA_BOOT_PASSWORD=password
keria start --boot 3903
```

To boot an agent, you can then either:

- Use basic auth in the Boot URL: `http://username:password@localhost:3903/boot`, most http clients will set the authorization header for you.
- Set the Authorization header in the boot request manually to `Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=`

We can also add a flag to completely disable the boot endpoint (https://github.com/WebOfTrust/keria/issues/203). E.g.

```
keria start --no-boot-endpoint
```

Or, 

```
export KERIA_DISABLE_BOOT_ENDPOINT=1
```

# Considerations

There are probably much more sophisticated ways to protect the boot endpoint. Please share your thoughts. In my opinion, this could be sufficient and will allow users to more easily deploy keria instances on the internet for testing purposes.

I have code and unit tests for this, so I can open a PR if we can agree this is a good idea.

**Comment by iFergal** [comment]
This makes sense to me for test servers deployed publicly. Would just want to make sure a simple username/pass doesn't end up becoming the norm.

I wrote a simple Spring Cloud Gateway service in Java that provisions one-time use boot URLs and emails them to clients. Used it to protect our infrastructure in an alpha program of our wallet, and it worked quite well. I can ask for it to be open sourced.

There are probably even safer ways to do it but it's a start.

**Comment by lenkan** [comment]
> Would just want to make sure a simple username/pass doesn't end up becoming the norm.

True. I think that can be handled by some clever naming of the configuration option. For example, a flag `--enable-test-boot-authentication` that must be set when `--boot-password` is set. Or, `--dangerously-set-boot-password <password>`  or something like that. :)

**Comment by lenkan** [comment]
Another note. It is quite common to password protect resources within a private network anyway. You would normally have password protection on your database servers for example. So perhaps it shouldn't be too inconvenient to protect it like this.
