### ISSUE TITLE
Crash when no witness endpoint

### ISSUE THREAD

**Issue by rodolfomiranda** [WebOfTrust/keria#54]
If an AID is incepted with a witness that does not respond, it crashes with `ERR: unable to query witness BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha, no http endpoint`

**Comment by rodolfomiranda** [comment]
Crashing in this line: https://github.com/WebOfTrust/keria/blob/62a344b6d5d953244fe0ceed51579519be079620/src/keria/app/agenting.py#L386

I don't know what to `yield` if we catch the exception

**Comment by lenkan** [comment]
@rodolfomiranda was this fixed by #92
