### ISSUE TITLE
Method to delete credentials from db

### ISSUE THREAD

**Issue by rodolfomiranda** [WebOfTrust/keria#79]
We may need a method for receivers of credential to delete the ones that are not longer needed/wanted.

**Comment by artikulkarni** [comment]
FYI - @m00sey

**Comment by m00sey** [comment]
I feel this can be an issued addressed by the UI, in terms of Read Update Nullify we don't want to forget about any information and given a holder can't revoke their own credentials I don't think it makes sense to delete them from an agent.

If they don't want to "see" them for me that's for the UI to determine.

**Comment by rodolfomiranda** [comment]
a flag may work so then we can use it to filter the `list`

**Comment by iFergal** [comment]
From dev call today, Phil and Sam have both suggested there's no security advantage of keeping the credentials around if the user no longer wants them, so a hard delete from the DB would be the easiest way forward.

It's more likely that an issuer will always keep credentials, and in some cases even based on legal requirement. So a holder could always re-retrieve the credential from the issuer if they really needed to.

I'll tackle this at some point soon as I need it.
