### ISSUE TITLE
Fix identifier create to error on reusing an AID alias

### ISSUE THREAD

**Issue by pfeairheller** [WebOfTrust/keria#85]
In `IdentifierCollectionEnd.on_post` method a check to see if name already needed at the beginning of the method and a 400 Bad Request exception should be raised on a second attempt to reuse a name (aid alias).

**Comment by rodolfomiranda** [comment]
I corrected that issue in https://github.com/WebOfTrust/keria/pull/78.

**Comment by lenkan** [comment]
This is already implemented https://github.com/WebOfTrust/keria/blob/cfc55d4de3948663e01a8f55c994112453efc17b/src/keria/app/aiding.py#L471-L474 and can be closed I think.

cc @2byrds
