### ISSUE TITLE
Liveness and readiness health check endpoints

### ISSUE THREAD

**Issue by kentbull** [WebOfTrust/keria#99]
Liveness checks and readiness checks facilitate stability and functionality for container deployment technology like Kubernetes for the following purposes:
1. Permitting routing of requests to a Kubernetes Pod only when it is ready to receive requests. This avoids unnecessarily causing client side errors or potential server side crashes.
2. Continuous health monitoring of pods. When a pod crashes or becomes unstable then Kubernetes will detect the poor health and automatically restart it. This may or may not make problems worse, though it usually makes them better.

Doing health checks in KERIA is challenging because of the following concerns:
1. A health check of the overall Agency is different than a health check on a particular agent.
2. A KERIA Agency may have hundreds of Agents. Should a global health check include an agent-specific check for every agent?
3. Which endpoint should the healthcheck be available on? 
   - 3901 (admin) 
   - 3902 (http) 
   - 3903 (boot)

**Comment by kentbull** [comment]
#97 shows an example of putting a health check on both 3901 and 3902.

**Comment by rodolfomiranda** [comment]
For the purpose of a health check that can detect readiness and crashes and be able to restart the process, I think a simple call  to the interfaces will suffice. You don't need to check independent agents.
I'd check the three ports independently so you can also detect that ports are opened correctly. That may be useful for load balancers.

**Comment by kentbull** [comment]
This was sufficiently addressed with https://github.com/WebOfTrust/keria/pull/144.
